name: fofa proxy
on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'
jobs:
  gen-proxy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Automated update by GitHub Actions' || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}